// Generates src/generated.ts from tokens.css so the Worker can inline the same
// tokens the admin SPA imports as a stylesheet. Run by `npm run build`;
// tokens.test.ts fails the suite if the checked-in output has drifted.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const here = (p) => fileURLToPath(new URL(p, import.meta.url))

/**
 * Comments and indentation are ~40% of tokens.css and this string is inlined
 * into every SSR'd document, so strip them. Deterministic: the drift test
 * re-runs this and compares.
 */
export function minifyCss(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\s*([{}:;,])\s*/g, '$1')
    .replace(/;\}/g, '}')
    .replace(/\s+/g, ' ')
    .trim()
}

export function render(css) {
  return `// GENERATED by packages/theme/build.mjs from tokens.css — do not edit.\n// Run \`npm run build -w @kms/theme\` after changing tokens.css.\nexport const tokensCss = ${JSON.stringify(minifyCss(css))}\n`
}

if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith('build.mjs')) {
  const css = readFileSync(here('tokens.css'), 'utf8')
  writeFileSync(here('src/generated.ts'), render(css))
  console.log('packages/theme: wrote src/generated.ts')
}
