// Regression (CFP-01): the Required toggle on a question row would
// "repeatedly revert to unchecked shortly after being checked, even
// immediately after a completed save" when two fields were checked in quick
// succession. Root cause: PUT /questions/:qid returns a FULL question-list
// snapshot, and the client applied whichever snapshot arrived last as-is.
// A snapshot generated by an earlier request (its own write committed, but
// read back before a *later* request's write had landed) could therefore
// overwrite the later request's already-confirmed change when it happened to
// resolve after it.
//
// This drives the real FormBuilder (not a stand-in), with updateQuestion
// mocked so the two responses resolve in an order — and with snapshots — that
// reproduce that race, then asserts both fields stay checked.

import { describe, expect, it, vi } from 'vitest'
import { fireEvent, render, screen, waitFor } from '@testing-library/preact'

interface MockQuestion {
  id: string
  form_id: string
  section: 'abstract' | 'participant'
  position: number
  required: boolean
  locked: boolean
  label: string
  help_text: string | null
  options: null
  max_chars: null
  visibility: null
  field_id: string
  field_key: string
  type: string
}

const FORM_ID = 'form-1'

// Function *declarations* (unlike const/let) are hoisted by the JS engine
// itself, so vi.hoisted's callback below — which vitest's transform moves
// above every other statement in this file — can safely call them despite
// being written after this point in the source.
function makeQuestion(id: string, label: string, position: number): MockQuestion {
  return {
    id,
    form_id: FORM_ID,
    section: 'abstract',
    position,
    required: false,
    locked: false,
    label,
    help_text: null,
    options: null,
    max_chars: null,
    visibility: null,
    field_id: `fld-${id}`,
    field_key: label.toLowerCase(),
    type: 'text',
  }
}

function makeBaseForm() {
  return {
    id: FORM_ID,
    internal_name: 'CFP',
    external_title: 'CFP',
    page_heading: 'Submit',
    welcome_message: null,
    welcome_message_visible: 0,
    collection_type: 'abstracts' as const,
    collect_participants: 0,
    status: 'open' as const,
    close_at: null,
    submission_limit: null,
    allow_multiple_drafts: 0,
    success_message: null,
    auto_redirect_to_portal: 0,
    routing_rules: null,
    participant_roles: [],
    confirmation_email_enabled: 0,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  }
}

const FORMAT_Q = makeQuestion('q-format', 'Format', 1)
const TITLE_Q = makeQuestion('q-title', 'Title', 2)

const { getFormDetail, getBuilderMeta, updateForm, addQuestion, deleteQuestion, reorderQuestions, updateQuestion } =
  vi.hoisted(() => ({
    getFormDetail: vi.fn(async () => ({
      form: makeBaseForm(),
      questions: [makeQuestion('q-format', 'Format', 1), makeQuestion('q-title', 'Title', 2)],
    })),
    getBuilderMeta: vi.fn(async () => ({ fields: [], tracks: [], tags: [], plans: [] })),
    updateForm: vi.fn(async () => ({ form: makeBaseForm() })),
    addQuestion: vi.fn(),
    deleteQuestion: vi.fn(),
    reorderQuestions: vi.fn(),
    updateQuestion: vi.fn(),
  }))

vi.mock('../api', () => ({
  getFormDetail,
  getBuilderMeta,
  updateForm,
  addQuestion,
  deleteQuestion,
  reorderQuestions,
  updateQuestion,
}))

import { FormBuilder } from './FormBuilder'

/** A deferred promise so the test controls resolution order explicitly. */
function deferred<T>() {
  let resolve!: (v: T) => void
  const promise = new Promise<T>((res) => {
    resolve = res
  })
  return { promise, resolve }
}

describe('FormBuilder — Required toggle race', () => {
  it('keeps both fields checked when their save responses resolve out of order', async () => {
    const formatDeferred = deferred<{ questions: MockQuestion[] }>()
    const titleDeferred = deferred<{ questions: MockQuestion[] }>()

    updateQuestion.mockImplementation((_formId: string, qid: string) => {
      if (qid === 'q-format') return formatDeferred.promise
      if (qid === 'q-title') return titleDeferred.promise
      throw new Error(`unexpected qid ${qid}`)
    })

    render(<FormBuilder formId={FORM_ID} eventSlug="evt" timezone="UTC" initialStep="abstract" onClose={() => {}} />)

    const checkboxes = await screen.findAllByRole('checkbox')
    const formatBox = checkboxes[0]!
    const titleBox = checkboxes[1]!
    expect(formatBox.closest('.qrow')?.textContent).toContain('Format')
    expect(titleBox.closest('.qrow')?.textContent).toContain('Title')

    // Check Format, then quickly check Title — both requests are now
    // in flight, and the UI must show both as checked immediately
    // (optimistic), before either response has arrived.
    fireEvent.click(formatBox)
    fireEvent.click(titleBox)
    expect((formatBox as HTMLInputElement).checked).toBe(true)
    expect((titleBox as HTMLInputElement).checked).toBe(true)

    // Title's request resolves first. Its snapshot reflects the DB as read
    // right after Title's own write — Format's write hadn't landed yet, so
    // the snapshot still shows Format unrequired. Under the old
    // "setQuestions(response) verbatim" code this would have reverted the
    // checkbox the user had just checked.
    titleDeferred.resolve({
      questions: [
        { ...FORMAT_Q, required: false },
        { ...TITLE_Q, required: true },
      ],
    })
    await waitFor(() => expect((titleBox as HTMLInputElement).checked).toBe(true))
    expect((formatBox as HTMLInputElement).checked).toBe(true)

    // Format's request resolves after — a "completed save" per the eval
    // report — with a snapshot that (by now) correctly reflects both writes.
    formatDeferred.resolve({
      questions: [
        { ...FORMAT_Q, required: true },
        { ...TITLE_Q, required: true },
      ],
    })
    await waitFor(() => expect((formatBox as HTMLInputElement).checked).toBe(true))

    // Both survive a subsequent refetch-style render — no lingering "pending
    // patch" state left corrupting later snapshots.
    expect((titleBox as HTMLInputElement).checked).toBe(true)
    expect((formatBox as HTMLInputElement).checked).toBe(true)
  })

  it('the earlier-issued request still wins if IT resolves last with a stale snapshot', async () => {
    const formatDeferred = deferred<{ questions: MockQuestion[] }>()
    const titleDeferred = deferred<{ questions: MockQuestion[] }>()

    updateQuestion.mockImplementation((_formId: string, qid: string) => {
      if (qid === 'q-format') return formatDeferred.promise
      if (qid === 'q-title') return titleDeferred.promise
      throw new Error(`unexpected qid ${qid}`)
    })

    render(<FormBuilder formId={FORM_ID} eventSlug="evt" timezone="UTC" initialStep="abstract" onClose={() => {}} />)
    const checkboxes = await screen.findAllByRole('checkbox')
    const formatBox = checkboxes[0]!
    const titleBox = checkboxes[1]!

    fireEvent.click(formatBox) // check Format first
    fireEvent.click(titleBox) // then Title, moments later

    // Format's response arrives LAST and, being the stale read, doesn't yet
    // know about Title's change either — but Title's own in-flight request
    // is what protects it, not Format's response.
    formatDeferred.resolve({
      questions: [
        { ...FORMAT_Q, required: true },
        { ...TITLE_Q, required: false },
      ],
    })
    await waitFor(() => expect((formatBox as HTMLInputElement).checked).toBe(true))
    // Title must still read checked — its own pending request re-asserts the
    // optimistic value on top of Format's stale snapshot.
    expect((titleBox as HTMLInputElement).checked).toBe(true)

    titleDeferred.resolve({
      questions: [
        { ...FORMAT_Q, required: true },
        { ...TITLE_Q, required: true },
      ],
    })
    await waitFor(() => expect((titleBox as HTMLInputElement).checked).toBe(true))
    expect((formatBox as HTMLInputElement).checked).toBe(true)
  })
})
