// GENERATED by scripts/build-manual.mjs from docs/manual/*.md — do not edit.
// Regenerate with `npm run build:manual` after changing the manual.

import type { ManualNavSection, ManualPageMeta } from './manualTypes'

export const MANUAL_NAV: ManualNavSection[] = [
  {
    "title": "Workflow guides",
    "items": [
      {
        "slug": "getting-started",
        "label": "Getting started",
        "blurb": "Signing in, events, roles, finding your way around",
        "depth": 0
      },
      {
        "slug": "call-for-speakers",
        "label": "Building your call for speakers",
        "blurb": "Form builder, conditional questions, publishing",
        "depth": 0
      },
      {
        "slug": "reviewing-submissions",
        "label": "Reviewing and deciding on submissions",
        "blurb": "The submissions list, scoring, accept/decline",
        "depth": 0
      },
      {
        "slug": "emails-and-reminders",
        "label": "Emails, reminders and calendar invites",
        "blurb": "Templates, automatic reminders, calendar invites",
        "depth": 0
      },
      {
        "slug": "speaker-portal",
        "label": "The speaker portal",
        "blurb": "What speakers see and do after acceptance",
        "depth": 0
      }
    ]
  },
  {
    "title": "Screen reference",
    "items": [
      {
        "slug": "dashboard",
        "label": "Dashboard",
        "blurb": "Today, Speaker Tracking, Submissions Pipeline, and the all-events board",
        "depth": 0
      },
      {
        "slug": "workspace",
        "label": "Workspace",
        "blurb": "Shared tab mechanics and the global anchor filter",
        "depth": 0
      },
      {
        "slug": "workspace-speakers",
        "label": "Speakers",
        "blurb": "The Speakers tab",
        "depth": 1
      },
      {
        "slug": "workspace-submissions",
        "label": "Submissions",
        "blurb": "The Submissions tab",
        "depth": 1
      },
      {
        "slug": "workspace-tasks",
        "label": "Tasks",
        "blurb": "The Tasks tab",
        "depth": 1
      },
      {
        "slug": "workspace-reviews",
        "label": "Reviews",
        "blurb": "The Reviews tab",
        "depth": 1
      },
      {
        "slug": "workspace-comments",
        "label": "Comments",
        "blurb": "The Comments tab",
        "depth": 1
      },
      {
        "slug": "workspace-messages",
        "label": "Messages",
        "blurb": "The Messages tab",
        "depth": 1
      },
      {
        "slug": "workspace-files",
        "label": "Files",
        "blurb": "The Files tab",
        "depth": 1
      },
      {
        "slug": "workspace-events",
        "label": "Events",
        "blurb": "The Events tab, and creating/switching events",
        "depth": 1
      },
      {
        "slug": "forms",
        "label": "Forms",
        "blurb": "The call-for-speakers form list and builder",
        "depth": 0
      },
      {
        "slug": "evaluation",
        "label": "Evaluation",
        "blurb": "Setting up review rounds and reviewers",
        "depth": 0
      },
      {
        "slug": "review",
        "label": "Review",
        "blurb": "The reviewer's own scoring workspace",
        "depth": 0
      },
      {
        "slug": "agenda",
        "label": "Agenda",
        "blurb": "Drag-and-drop scheduling and conflict resolution",
        "depth": 0
      },
      {
        "slug": "greenroom",
        "label": "Green Room",
        "blurb": "The day-of run-of-show screen",
        "depth": 0
      },
      {
        "slug": "pipeline",
        "label": "Pipeline",
        "blurb": "The org-wide speaker/sponsor prospecting board",
        "depth": 0
      },
      {
        "slug": "embeds",
        "label": "Embeds",
        "blurb": "Generating embeddable widgets and feeds",
        "depth": 0
      },
      {
        "slug": "settings",
        "label": "Settings",
        "blurb": "Every settings card: tokens, rooms/tracks, fields, statuses, templates, chase mode",
        "depth": 0
      }
    ]
  },
  {
    "title": "Lifecycle guides",
    "items": [
      {
        "slug": "contact-lifecycle",
        "label": "Contact lifecycle",
        "blurb": "A person: prospect → attached to an event → speaker status → portal → tasks → arrival",
        "depth": 0
      },
      {
        "slug": "submission-lifecycle",
        "label": "Submission lifecycle",
        "blurb": "A proposal: draft → decision → scheduled → published",
        "depth": 0
      },
      {
        "slug": "event-lifecycle",
        "label": "Event lifecycle",
        "blurb": "An event: created → configured → open → live → wrapped up",
        "depth": 0
      }
    ]
  }
]

export const MANUAL_PAGE_META: ManualPageMeta[] = [
  {
    "slug": "index",
    "title": "User Manual"
  },
  {
    "slug": "agenda",
    "title": "Agenda"
  },
  {
    "slug": "call-for-speakers",
    "title": "Building your call for speakers"
  },
  {
    "slug": "contact-lifecycle",
    "title": "Contact lifecycle"
  },
  {
    "slug": "dashboard",
    "title": "Dashboard"
  },
  {
    "slug": "emails-and-reminders",
    "title": "Emails, reminders and calendar invites"
  },
  {
    "slug": "embeds",
    "title": "Embeds"
  },
  {
    "slug": "evaluation",
    "title": "Evaluation"
  },
  {
    "slug": "event-lifecycle",
    "title": "Event lifecycle"
  },
  {
    "slug": "forms",
    "title": "Forms"
  },
  {
    "slug": "getting-started",
    "title": "Getting started"
  },
  {
    "slug": "greenroom",
    "title": "Green Room"
  },
  {
    "slug": "pipeline",
    "title": "Pipeline"
  },
  {
    "slug": "review",
    "title": "Review"
  },
  {
    "slug": "reviewing-submissions",
    "title": "Reviewing and deciding on submissions"
  },
  {
    "slug": "settings",
    "title": "Settings"
  },
  {
    "slug": "speaker-portal",
    "title": "The speaker portal"
  },
  {
    "slug": "submission-lifecycle",
    "title": "Submission lifecycle"
  },
  {
    "slug": "workspace",
    "title": "Workspace"
  },
  {
    "slug": "workspace-comments",
    "title": "Workspace → Comments"
  },
  {
    "slug": "workspace-events",
    "title": "Workspace → Events"
  },
  {
    "slug": "workspace-files",
    "title": "Workspace → Files"
  },
  {
    "slug": "workspace-messages",
    "title": "Workspace → Messages"
  },
  {
    "slug": "workspace-reviews",
    "title": "Workspace → Reviews"
  },
  {
    "slug": "workspace-speakers",
    "title": "Workspace → Speakers"
  },
  {
    "slug": "workspace-submissions",
    "title": "Workspace → Submissions"
  },
  {
    "slug": "workspace-tasks",
    "title": "Workspace → Tasks"
  }
]
