// Converts docs/manual/*.md into the two TypeScript modules the admin SPA's
// Help section imports:
//
//   apps/admin/src/help/manualNav.generated.ts    — nav tree + slug/title list
//   apps/admin/src/help/manualPages.generated.ts  — the rendered HTML bodies
//
// Split in two on purpose: the nav is tiny and statically imported by the
// shell (the '?' button needs slug→title), while the ~110KB of page HTML is
// dynamically imported by HelpSection so Vite gives it its own chunk and the
// admin bundle does not carry the manual for users who never open it.
//
// Both files are committed, so `tsc`/`vitest` work on a fresh clone without
// running the build; `npm run build:manual` regenerates them and is wired into
// `npm run build` ahead of build:admin.
//
// The markdown conversion itself lives in scripts/manual-markdown.mjs — pure,
// and tested there. This file is only the I/O around it.

import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { INDEX_SLUG, parseNav, renderMarkdown } from './manual-markdown.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const MANUAL_DIR = join(HERE, '..', 'docs', 'manual')
const OUT_DIR = join(HERE, '..', 'apps', 'admin', 'src', 'help')

const slugOf = (filename) => (filename === 'README.md' ? INDEX_SLUG : filename.slice(0, -3))

const files = readdirSync(MANUAL_DIR).filter((name) => name.endsWith('.md'))
const slugs = new Set(files.map(slugOf))

// Index first, then alphabetical — the order the generated module's key order
// takes, so a regenerated file diffs only where the manual actually changed.
const pages = files
  .map((name) => ({ slug: slugOf(name), ...renderMarkdown(readFileSync(join(MANUAL_DIR, name), 'utf8'), slugs) }))
  .sort((a, b) => (a.slug === INDEX_SLUG ? -1 : b.slug === INDEX_SLUG ? 1 : a.slug < b.slug ? -1 : 1))

const nav = parseNav(readFileSync(join(MANUAL_DIR, 'README.md'), 'utf8'), slugs)

const BANNER = `// GENERATED by scripts/build-manual.mjs from docs/manual/*.md — do not edit.
// Regenerate with \`npm run build:manual\` after changing the manual.
`

mkdirSync(OUT_DIR, { recursive: true })

writeFileSync(
  join(OUT_DIR, 'manualNav.generated.ts'),
  `${BANNER}
import type { ManualNavSection, ManualPageMeta } from './manualTypes'

export const MANUAL_NAV: ManualNavSection[] = ${JSON.stringify(nav, null, 2)}

export const MANUAL_PAGE_META: ManualPageMeta[] = ${JSON.stringify(
    pages.map((page) => ({ slug: page.slug, title: page.title })),
    null,
    2,
  )}
`,
  'utf8',
)

writeFileSync(
  join(OUT_DIR, 'manualPages.generated.ts'),
  `${BANNER}
import type { ManualPage } from './manualTypes'

export const MANUAL_PAGES: Record<string, ManualPage> = ${JSON.stringify(
    Object.fromEntries(pages.map((page) => [page.slug, page])),
    null,
    2,
  )}
`,
  'utf8',
)

console.log(`build-manual: ${pages.length} pages, ${nav.length} nav sections`)
